package com.Dao;

import com.Dao.DataObject.ActivityDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ActivityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int deleteByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insert(ActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insertSelective(ActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    ActivityDO selectByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKeySelective(ActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKey(ActivityDO record);
}