package com.Dao;

import com.Dao.DataObject.AddressDO;

import java.util.ArrayList;

public interface AddressDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressInfo
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    int deleteByPrimaryKey(Integer addressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressInfo
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    int insert(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressInfo
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    int insertSelective(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressInfo
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    AddressDO selectByPrimaryKey(Integer addressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressInfo
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    int updateByPrimaryKeySelective(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressInfo
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    int updateByPrimaryKey(AddressDO record);

    ArrayList<AddressDO> selectByUserid(int userid);
}