package com.Dao;

import com.Dao.DataObject.BrandDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;

@Mapper
public interface BrandDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brandInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int deleteByPrimaryKey(Integer brandid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brandInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insert(BrandDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brandInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insertSelective(BrandDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brandInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    BrandDO selectByPrimaryKey(Integer brandid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brandInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKeySelective(BrandDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brandInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKey(BrandDO record);

    ArrayList<BrandDO> selectLimitPage(@Param("limit") int limit, @Param("page") int page);

    ArrayList<BrandDO> selectAll();
}