package com.Dao;

import com.Dao.DataObject.evaluateImageDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface evaluateImageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluateImageInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluateImageInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insert(evaluateImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluateImageInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insertSelective(evaluateImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluateImageInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    evaluateImageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluateImageInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKeySelective(evaluateImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluateImageInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKey(evaluateImageDO record);
}