package com.Dao;

import com.Dao.DataObject.ItemTypeDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.ArrayList;

@Mapper

public interface ItemTypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemType
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemType
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insert(ItemTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemType
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insertSelective(ItemTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemType
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    ItemTypeDO selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemType
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKeySelective(ItemTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemType
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKey(ItemTypeDO record);

    ArrayList<ItemTypeDO> getSonTypeByID(int id);

    ArrayList<ItemTypeDO> getType(int grade);
}