package com.Dao;

import com.Dao.DataObject.ItemDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;

@Mapper
public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    ItemDO selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKey(ItemDO record);

    ArrayList<ItemDO> selectList(@Param("title") String title, @Param("brand") String brand, @Param("type") String type,
                                 @Param("page") int page, @Param("limit") int limit);
    ArrayList<ItemDO> selectListByBrand(@Param("value") String value,@Param("page") int page,@Param("limit") int i);
    ArrayList<ItemDO> selectListByType(@Param("value") String value,@Param("page") int page,@Param("limit") int i);
    ArrayList<ItemDO> selectListByTitle(@Param("value") String value,@Param("page") int page,@Param("limit") int i);
    ArrayList<ItemDO> select( @Param("page") int page,@Param("limit") int i);
}