package com.Dao;

import com.Dao.DataObject.ItemAttributesDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;

@Mapper
public interface ItemAttributesDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemAttributesInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int deleteByPrimaryKey(Integer itemattributesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemAttributesInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insert(ItemAttributesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemAttributesInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insertSelective(ItemAttributesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemAttributesInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    ItemAttributesDO selectByPrimaryKey(Integer itemattributesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemAttributesInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKeySelective(ItemAttributesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemAttributesInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKey(ItemAttributesDO record);

    ArrayList<ItemAttributesDO> seletByItemID(Integer itemid);

    int reduceShock(@Param("itemAttributesid") Integer itemattributesid, @Param("amount") Integer amount);
}