package com.Dao;

import com.Dao.DataObject.ItemEvaluateDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ItemEvaluateDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemEvaluateInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemEvaluateInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insert(ItemEvaluateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemEvaluateInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insertSelective(ItemEvaluateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemEvaluateInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    ItemEvaluateDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemEvaluateInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKeySelective(ItemEvaluateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemEvaluateInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKey(ItemEvaluateDO record);
}