package com.Dao;

import com.Dao.DataObject.OrderAttributesDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderAttributesDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderAttributesInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insert(OrderAttributesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderAttributesInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insertSelective(OrderAttributesDO record);

    int updateStateByOrderId(@Param("orderid") String orderid, @Param("state") String state);

    int deleteByOrderid(String orderid);
}