package com.Dao;

import com.Dao.DataObject.OrderDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;

@Mapper
public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int deleteByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    OrderDO selectByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderInfo
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    int updateByPrimaryKey(OrderDO record);

    int updateStateByOrderId(@Param("orderid") String orderid, @Param("state") String state);

    ArrayList<OrderDO> selectByUserid(int userid);
}