package com.Dao.DataObject;

public class ActivityDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activityInfo.activityid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer activityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activityInfo.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activityInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activityInfo.beginDate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String begindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activityInfo.endDate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activityInfo.amount
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activityInfo.descrption
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String descrption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activityInfo.state
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activityInfo.activityid
     *
     * @return the value of activityInfo.activityid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activityInfo.activityid
     *
     * @param activityid the value for activityInfo.activityid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activityInfo.title
     *
     * @return the value of activityInfo.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activityInfo.title
     *
     * @param title the value for activityInfo.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activityInfo.itemid
     *
     * @return the value of activityInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activityInfo.itemid
     *
     * @param itemid the value for activityInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activityInfo.beginDate
     *
     * @return the value of activityInfo.beginDate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activityInfo.beginDate
     *
     * @param begindate the value for activityInfo.beginDate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setBegindate(String begindate) {
        this.begindate = begindate == null ? null : begindate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activityInfo.endDate
     *
     * @return the value of activityInfo.endDate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activityInfo.endDate
     *
     * @param enddate the value for activityInfo.endDate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate == null ? null : enddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activityInfo.amount
     *
     * @return the value of activityInfo.amount
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activityInfo.amount
     *
     * @param amount the value for activityInfo.amount
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activityInfo.descrption
     *
     * @return the value of activityInfo.descrption
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getDescrption() {
        return descrption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activityInfo.descrption
     *
     * @param descrption the value for activityInfo.descrption
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setDescrption(String descrption) {
        this.descrption = descrption == null ? null : descrption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activityInfo.state
     *
     * @return the value of activityInfo.state
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activityInfo.state
     *
     * @param state the value for activityInfo.state
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}