package com.Dao.DataObject;

public class AddressDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressInfo.addressid
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    private Integer addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressInfo.userid
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressInfo.default
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    private Integer default_;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressInfo.province
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressInfo.city
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressInfo.country
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addressInfo.specificAddress
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    private String specificaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressInfo.addressid
     *
     * @return the value of addressInfo.addressid
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressInfo.addressid
     *
     * @param addressid the value for addressInfo.addressid
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressInfo.userid
     *
     * @return the value of addressInfo.userid
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressInfo.userid
     *
     * @param userid the value for addressInfo.userid
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressInfo.default
     *
     * @return the value of addressInfo.default
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public Integer getDefault() {
        return default_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressInfo.default
     *
     * @param default the value for addressInfo.default
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public void setDefault(Integer default_) {
        this.default_ = default_;

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressInfo.province
     *
     * @return the value of addressInfo.province
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressInfo.province
     *
     * @param province the value for addressInfo.province
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressInfo.city
     *
     * @return the value of addressInfo.city
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressInfo.city
     *
     * @param city the value for addressInfo.city
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressInfo.country
     *
     * @return the value of addressInfo.country
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressInfo.country
     *
     * @param country the value for addressInfo.country
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addressInfo.specificAddress
     *
     * @return the value of addressInfo.specificAddress
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public String getSpecificaddress() {
        return specificaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addressInfo.specificAddress
     *
     * @param specificaddress the value for addressInfo.specificAddress
     *
     * @mbg.generated Mon May 24 16:38:58 CST 2021
     */
    public void setSpecificaddress(String specificaddress) {
        this.specificaddress = specificaddress == null ? null : specificaddress.trim();
    }
}