package com.Dao.DataObject;

import com.Controller.ViewObject.BrandVo;

public class BrandDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brandInfo.brandid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer brandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brandInfo.name
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brandInfo.description
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String description;

    public BrandDO() {

    }

    public BrandDO(BrandVo brandVo) {
        this.brandid=brandVo.getBrandid();
        this.name=brandVo.getName();
        this.description=brandVo.getDescription();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brandInfo.brandid
     *
     * @return the value of brandInfo.brandid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */

    public Integer getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brandInfo.brandid
     *
     * @param brandid the value for brandInfo.brandid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setBrandid(Integer brandid) {
        this.brandid = brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brandInfo.name
     *
     * @return the value of brandInfo.name
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brandInfo.name
     *
     * @param name the value for brandInfo.name
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brandInfo.description
     *
     * @return the value of brandInfo.description
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brandInfo.description
     *
     * @param description the value for brandInfo.description
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}