package com.Dao.DataObject;

public class evaluateImageDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluateImageInfo.id
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluateImageInfo.evaluateid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer evaluateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluateImageInfo.imgUrl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluateImageInfo.id
     *
     * @return the value of evaluateImageInfo.id
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluateImageInfo.id
     *
     * @param id the value for evaluateImageInfo.id
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluateImageInfo.evaluateid
     *
     * @return the value of evaluateImageInfo.evaluateid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getEvaluateid() {
        return evaluateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluateImageInfo.evaluateid
     *
     * @param evaluateid the value for evaluateImageInfo.evaluateid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setEvaluateid(Integer evaluateid) {
        this.evaluateid = evaluateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluateImageInfo.imgUrl
     *
     * @return the value of evaluateImageInfo.imgUrl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluateImageInfo.imgUrl
     *
     * @param imgurl the value for evaluateImageInfo.imgUrl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }
}