package com.Dao.DataObject;

import com.Service.Model.ItemAttributesModel;

import java.math.BigDecimal;

public class ItemAttributesDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemAttributesInfo.itemAttributesid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer itemattributesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemAttributesInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemAttributesInfo.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemAttributesInfo.price
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemAttributesInfo.imgurl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemAttributesInfo.stock
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer stock;

    public ItemAttributesDO() {
    }

    public ItemAttributesDO(ItemAttributesModel itemAttributesModel) {
        this.itemattributesid=itemAttributesModel.getItemattributesid();
        this.itemid=itemAttributesModel.getItemid();
        this.title=itemAttributesModel.getTitle();
        this.price=itemAttributesModel.getPrice();
        this.imgurl=itemAttributesModel.getImgurl();
        this.stock=itemAttributesModel.getStock();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemAttributesInfo.itemAttributesid
     *
     * @return the value of itemAttributesInfo.itemAttributesid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getItemattributesid() {
        return itemattributesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemAttributesInfo.itemAttributesid
     *
     * @param itemattributesid the value for itemAttributesInfo.itemAttributesid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setItemattributesid(Integer itemattributesid) {
        this.itemattributesid = itemattributesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemAttributesInfo.itemid
     *
     * @return the value of itemAttributesInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemAttributesInfo.itemid
     *
     * @param itemid the value for itemAttributesInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemAttributesInfo.title
     *
     * @return the value of itemAttributesInfo.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemAttributesInfo.title
     *
     * @param title the value for itemAttributesInfo.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemAttributesInfo.price
     *
     * @return the value of itemAttributesInfo.price
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemAttributesInfo.price
     *
     * @param price the value for itemAttributesInfo.price
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemAttributesInfo.imgurl
     *
     * @return the value of itemAttributesInfo.imgurl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemAttributesInfo.imgurl
     *
     * @param imgurl the value for itemAttributesInfo.imgurl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemAttributesInfo.stock
     *
     * @return the value of itemAttributesInfo.stock
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemAttributesInfo.stock
     *
     * @param stock the value for itemAttributesInfo.stock
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}