package com.Dao.DataObject;

import com.Service.Model.ItemTypeModel;

public class ItemTypeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemType.typeid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemType.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemType.level
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemType.fatherid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer fatherid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemType.typeid
     *
     * @return the value of itemType.typeid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public ItemTypeDO() {
    }
    public ItemTypeDO(ItemTypeModel model) {
        this.typeid=model.getTypeid();
        this.title=model.getTitle();
        this.level=model.getLevel();
        this.fatherid=model.getFatherid();
    }
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemType.typeid
     *
     * @param typeid the value for itemType.typeid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemType.title
     *
     * @return the value of itemType.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemType.title
     *
     * @param title the value for itemType.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemType.level
     *
     * @return the value of itemType.level
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemType.level
     *
     * @param level the value for itemType.level
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemType.fatherid
     *
     * @return the value of itemType.fatherid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getFatherid() {
        return fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemType.fatherid
     *
     * @param fatherid the value for itemType.fatherid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setFatherid(Integer fatherid) {
        this.fatherid = fatherid;
    }
}