package com.Dao.DataObject;

import com.Controller.ViewObject.ItemVo;
import com.Service.Model.ItemModel;

import java.math.BigDecimal;

public class ItemDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.descrption
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String descrption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.sales
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.brandid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.typeid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.imgurl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.maxprice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private BigDecimal maxprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.minprice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private BigDecimal minprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemInfo.activityid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer activityid;

    public ItemDO() {
    }
    public ItemDO(ItemModel model) {
        this.itemid=model.getItemid();
        this.title=model.getTitle();
        this.descrption=model.getDescrption();
        this.sales=model.getSales();
        this.brand=model.getBrand();
        this.type = model.getType();
        this.imgurl=model.getImgurl();
        this.maxprice=model.getMaxprice();
        this.minprice=model.getMinprice();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemInfo.itemid
     *
     * @return the value of itemInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemInfo.itemid
     *
     * @param itemid the value for itemInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemInfo.title
     *
     * @return the value of itemInfo.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemInfo.title
     *
     * @param title the value for itemInfo.title
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemInfo.descrption
     *
     * @return the value of itemInfo.descrption
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getDescrption() {
        return descrption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemInfo.descrption
     *
     * @param descrption the value for itemInfo.descrption
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setDescrption(String descrption) {
        this.descrption = descrption == null ? null : descrption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemInfo.sales
     *
     * @return the value of itemInfo.sales
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemInfo.sales
     *
     * @param sales the value for itemInfo.sales
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemInfo.brandid
     *
     * @return the value of itemInfo.brandid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemInfo.imgurl
     *
     * @return the value of itemInfo.imgurl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemInfo.imgurl
     *
     * @param imgurl the value for itemInfo.imgurl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemInfo.maxprice
     *
     * @return the value of itemInfo.maxprice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public BigDecimal getMaxprice() {
        return maxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemInfo.maxprice
     *
     * @param maxprice the value for itemInfo.maxprice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setMaxprice(BigDecimal maxprice) {
        this.maxprice = maxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemInfo.minprice
     *
     * @return the value of itemInfo.minprice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public BigDecimal getMinprice() {
        return minprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemInfo.minprice
     *
     * @param minprice the value for itemInfo.minprice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setMinprice(BigDecimal minprice) {
        this.minprice = minprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemInfo.activityid
     *
     * @return the value of itemInfo.activityid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemInfo.activityid
     *
     * @param activityid the value for itemInfo.activityid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }
}