package com.Dao.DataObject;

public class ItemEvaluateDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemEvaluateInfo.id
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemEvaluateInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemEvaluateInfo.itemAttributesid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer itemattributesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemEvaluateInfo.level
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemEvaluateInfo.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemEvaluateInfo.descrption
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String descrption;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemEvaluateInfo.id
     *
     * @return the value of itemEvaluateInfo.id
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemEvaluateInfo.id
     *
     * @param id the value for itemEvaluateInfo.id
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemEvaluateInfo.itemid
     *
     * @return the value of itemEvaluateInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemEvaluateInfo.itemid
     *
     * @param itemid the value for itemEvaluateInfo.itemid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemEvaluateInfo.itemAttributesid
     *
     * @return the value of itemEvaluateInfo.itemAttributesid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getItemattributesid() {
        return itemattributesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemEvaluateInfo.itemAttributesid
     *
     * @param itemattributesid the value for itemEvaluateInfo.itemAttributesid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setItemattributesid(Integer itemattributesid) {
        this.itemattributesid = itemattributesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemEvaluateInfo.level
     *
     * @return the value of itemEvaluateInfo.level
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemEvaluateInfo.level
     *
     * @param level the value for itemEvaluateInfo.level
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemEvaluateInfo.userid
     *
     * @return the value of itemEvaluateInfo.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemEvaluateInfo.userid
     *
     * @param userid the value for itemEvaluateInfo.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemEvaluateInfo.descrption
     *
     * @return the value of itemEvaluateInfo.descrption
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getDescrption() {
        return descrption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemEvaluateInfo.descrption
     *
     * @param descrption the value for itemEvaluateInfo.descrption
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setDescrption(String descrption) {
        this.descrption = descrption == null ? null : descrption.trim();
    }
}