package com.Dao.DataObject;

import java.math.BigDecimal;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.orderid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.allPrice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private BigDecimal allprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.finalAllPrice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private BigDecimal finalallprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.createDate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.state
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.orderNumber
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.arrivalAddress
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String arrivaladdress;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.orderid
     *
     * @return the value of orderInfo.orderid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.orderid
     *
     * @param orderid the value for orderInfo.orderid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.userid
     *
     * @return the value of orderInfo.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.userid
     *
     * @param userid the value for orderInfo.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.allPrice
     *
     * @return the value of orderInfo.allPrice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public BigDecimal getAllprice() {
        return allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.allPrice
     *
     * @param allprice the value for orderInfo.allPrice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setAllprice(BigDecimal allprice) {
        this.allprice = allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.finalAllPrice
     *
     * @return the value of orderInfo.finalAllPrice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public BigDecimal getFinalallprice() {
        return finalallprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.finalAllPrice
     *
     * @param finalallprice the value for orderInfo.finalAllPrice
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setFinalallprice(BigDecimal finalallprice) {
        this.finalallprice = finalallprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.createDate
     *
     * @return the value of orderInfo.createDate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.createDate
     *
     * @param createdate the value for orderInfo.createDate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.state
     *
     * @return the value of orderInfo.state
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.state
     *
     * @param state the value for orderInfo.state
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.orderNumber
     *
     * @return the value of orderInfo.orderNumber
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.orderNumber
     *
     * @param ordernumber the value for orderInfo.orderNumber
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber == null ? null : ordernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.arrivalAddress
     *
     * @return the value of orderInfo.arrivalAddress
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getArrivaladdress() {
        return arrivaladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.arrivalAddress
     *
     * @param arrivaladdress the value for orderInfo.arrivalAddress
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setArrivaladdress(String arrivaladdress) {
        this.arrivaladdress = arrivaladdress == null ? null : arrivaladdress.trim();
    }
}