package com.Dao.DataObject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.telphone
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.username
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.birthdate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.sex
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.imgurl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.identity
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String identity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.userid
     *
     * @return the value of userInfo.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.userid
     *
     * @param userid the value for userInfo.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.telphone
     *
     * @return the value of userInfo.telphone
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.telphone
     *
     * @param telphone the value for userInfo.telphone
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.username
     *
     * @return the value of userInfo.username
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.username
     *
     * @param username the value for userInfo.username
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.birthdate
     *
     * @return the value of userInfo.birthdate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.birthdate
     *
     * @param birthdate the value for userInfo.birthdate
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate == null ? null : birthdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.sex
     *
     * @return the value of userInfo.sex
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.sex
     *
     * @param sex the value for userInfo.sex
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.imgurl
     *
     * @return the value of userInfo.imgurl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.imgurl
     *
     * @param imgurl the value for userInfo.imgurl
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.identity
     *
     * @return the value of userInfo.identity
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.identity
     *
     * @param identity the value for userInfo.identity
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }
}