package com.Dao.DataObject;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userPassword.id
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userPassword.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userPassword.encryptpassword
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    private String encryptpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userPassword.id
     *
     * @return the value of userPassword.id
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userPassword.id
     *
     * @param id the value for userPassword.id
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userPassword.userid
     *
     * @return the value of userPassword.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userPassword.userid
     *
     * @param userid the value for userPassword.userid
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userPassword.encryptpassword
     *
     * @return the value of userPassword.encryptpassword
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public String getEncrptPassword() {
        return encryptpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userPassword.encryptpassword
     *
     * @param encryptpassword the value for userPassword.encryptpassword
     *
     * @mbg.generated Sun May 23 15:43:17 CST 2021
     */
    public void setEncrptPassword(String encryptpassword) {
        this.encryptpassword = encryptpassword == null ? null : encryptpassword.trim();
    }
}